// src/utils/cssProperties.js

// A comprehensive list of common CSS properties for layout, spacing, and more.
export const allCSSProperties = [
  // Spacing
  'padding',
  'padding-top',
  'padding-right',
  'padding-bottom',
  'padding-left',
  'padding-inline',
  'padding-inline-start',
  'padding-inline-end',
  'padding-block',
  'padding-block-start',
  'padding-block-end',
  'margin',
  'margin-top',
  'margin-right',
  'margin-bottom',
  'margin-left',
  'margin-inline',
  'margin-inline-start',
  'margin-inline-end',
  'margin-block',
  'margin-block-start',
  'margin-block-end',

  // Layout & Sizing
  'width',
  'height',
  'min-width',
  'min-height',
  'max-width',
  'max-height',
  'display',
  'position',
  'top',
  'right',
  'bottom',
  'left',
  'inset',
  'inset-inline-start',
  'inset-inline-end',
  'inset-block-start',
  'inset-block-end',
  'z-index',
  'overflow',
  'overflow-x',
  'overflow-y',
  'float',
  'clear',
  'box-sizing',
  
  // Flexbox
  'flex',
  'flex-basis',
  'flex-direction',
  'flex-flow',
  'flex-grow',
  'flex-shrink',
  'flex-wrap',
  'order',
  'gap',
  'row-gap',
  'column-gap',
  'justify-content',
  'align-items',
  'align-content',
  'align-self',

  // Grid
  'grid',
  'grid-template',
  'grid-template-columns',
  'grid-template-rows',
  'grid-template-areas',
  'grid-auto-columns',
  'grid-auto-rows',
  'grid-auto-flow',
  'grid-column',
  'grid-column-start',
  'grid-column-end',
  'grid-row',
  'grid-row-start',
  'grid-row-end',
  'grid-area',
  'justify-items',
  'justify-self',
  
  // Typography
  'font-size',
  'font-weight',
  'font-family',
  'line-height',
  'letter-spacing',
  'text-align',
  'text-decoration',
  'text-transform',
  'color',
  'white-space',
  
  // Background & Borders
  'background',
  'background-color',
  'background-image',
  'background-position',
  'background-size',
  'border',
  'border-width',
  'border-style',
  'border-color',
  'border-radius',
  'border-top',
  'border-right',
  'border-bottom',
  'border-left',

  // Transitions & Transforms
  'transition',
  'transform',
  'transform-origin',
  
  // Other
  'opacity',
  'box-shadow',
  'cursor',
  'list-style',
];

// We keep the original for any logic that might specifically want only spacing.
export const spacingProperties = [
  'padding',
  'padding-top',
  'padding-right',
  'padding-bottom',
  'padding-left',
  'margin',
  'margin-top',
  'margin-right',
  'margin-bottom',
  'margin-left',
  'gap',
  'row-gap',
  'column-gap',
  'width',
  'height',
  'min-width',
  'min-height',
  'max-width',
  'max-height',
  'top',
  'right',
  'bottom',
  'left',
  'font-size',
  'line-height',
  'border-width',
  'border-top-width',
  'border-right-width',
  'border-bottom-width',
  'border-left-width',
  'outline-width',
  'flex-basis',
];